stages:
- name: build image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: stefanfritsch/r_barebones_statup:${CICD_GIT_BRANCH}.${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: index.docker.io
timeout: 60
branch:
  include:
  - 3.5.3
notification: {}
