stages:
- name: docker on tag
  steps:
  - runScriptConfig:
      image: stefanfritsch/kaniko-maximizer_statup:latest
      shellScript: |-
        ls -l /

        /kaniko/build-image.sh
    env:
      CACHE_REPO: stefanfritsch/r_barebones_statup_cache
      REPO: stefanfritsch/r_barebones_statup
    envFrom:
    - sourceName: pipeline-registry-dockerhub
      sourceKey: kaniko_docker_configjson
      targetKey: DOCKER_CONFIG_JSON
  when:
    event:
      include:
      - tag
timeout: 60
branch:
  include:
  - 3.5.3
notification: {}
